name: Actions Workflow

on:

  repository_dispatch:
    type: [build]
  # schedule:
  #   - cron: "10 12 * * *"

  push:

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:

     - name: ; List Files
       run: |
        ls 
        pwd
        echo $GITHUB_SHA
        echo $GITHUB_WORKFLOW
        echo $GITHUB_ACTOR


     - name: Checkout
       uses: actions/checkout@v1     #this will authenticate your repository, and will have some id and we can checkout to that particular commit and pull the code (git fetch/pull) 
     - name: List files after checkout
       run: |
        ls -la
        pwd
     - name: Simple JS Action
       id: greet
       uses: actions/hello-world-javascript-action@main
       with:
         who-to-greet: 'Anurag, please merge the PR'

     - name: Log Greeting time
       run: echo "${{ steps.greet.outputs.time }}"        #output of previous action (greeting Anurag). You need to give an id to the action
                                                          # to reference it for the output. 
  
