name: Shell Commands    #this is the name of the workflow. Workflow can have multiple jobs under it. Like this one has 2 jobs
                        #echo a string and multiline script

on: [push]            #this job will run on any 'push' event/action

jobs:
  run-shell-command:            #name of the job
    runs-on: ubuntu-latest
    steps:                       #use an array of steps
      - name: echo a string
        run: echo "Hello World"
      
      - name: multiline script
        run: |                    #pipe function to run multiple commands
          node -v 
          npm -v
      
      - name: python Command
        run: |
          import platform
          print(platform.processor())
        shell: python


